name: build-chatbot
on: { push: { branches: ["main"] } }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/pickl-chatbot:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/pickl-chatbot:${{ github.sha }} \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server (pull & restart only langchain)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/app
            docker compose pull langchain
            docker compose up -d langchain
            docker compose ps