name: build-chatbot
on: { push: { branches: [ "main" ] } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/pickl-chatbot:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/pickl-chatbot:${{ github.sha }} \
            --push .